FROM ubuntu:18.04

# Create local user accounts
RUN adduser alice --gecos --disabled-password && \
    adduser bob --gecos --disabled-password && \
    adduser jupyter --gecos --disabled-password

RUN apt-get update && \
    apt-get install --no-install-recommends -y \
        libpam-krb5 \
        krb5-user \
        wget \
        bzip2 \
	gcc-6 \
        ca-certificates

# Install miniconda to get jupyterhub
RUN wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh  && \
    echo '122c8c9beb51e124ab32a0fa6426c656 */tmp/miniconda.sh' | md5sum -c - && \
    bash /tmp/miniconda.sh -f -b -p /opt/conda && \
    rm /tmp/miniconda.sh

RUN /opt/conda/bin/conda install --yes -c conda-forge \
    python=3.7 \
    notebook=* \
    idna=* \
    jupyterhub=* \
    pamela=* \
    sudospawner=* && \
    /opt/conda/bin/conda clean -tipsy

# Configure kerberos
COPY krb5.conf /etc/
COPY kdc.conf /etc/krb5kdc/

# PAM_KRB5CCNAME is not set when opening the session for some reason and so we have to
# explicitly retain the cache created during auth instead.
# Also, turn on pam debug logging
RUN sed -i 's$1000$1000 ccache=/tmp/krb5cc_%u retain_after_close debug$' /etc/pam.d/common-auth
RUN sed -i 's$1000$1000 debug$' /etc/pam.d/common-session

# Setup for the sudospawner case
RUN mkdir -p /opt/jupyterhub && \
    chown jupyter:jupyter /opt/jupyterhub && \
    echo 'jupyter ALL=(ALL:ALL) NOPASSWD:/opt/conda/bin/sudospawner' >> /etc/sudoers

# Add the jupyterhub config
COPY jupyterhub_config.py /opt/jupyterhub/
COPY jupyterhub_sudo_config.py /opt/jupyterhub/
COPY hub.sh /opt/jupyterhub/

# Add custom sudospawner script
COPY sudospawner-singleuser /opt/conda/bin/

EXPOSE 8000
WORKDIR /opt/jupyterhub
CMD ["./hub.sh"]
